### ISSUE TITLE
any plan for gulp2grunt?

### ISSUE THREAD

**Issue by ultrasonicsoft** [omouse/grunt2gulp.js#17]
Hi there,

Could you please let me know if there is any reverse package available for gulp to grunt?

Thanks!

**Comment by omouse** [comment]
as far as I know no such package exists, it would be a neat project to try and make one though!

**Comment by omouse** [comment]
was toying with the idea of something like [pandoc](http://pandoc.org/) but for JS task runners; would be nice to be able to easily move projects from one build system to another if needed (say for moving old projects from Grunt to Gulp or to Broccoli)

**Comment by omouse** [comment]
will reopen if someone thinks this would be really useful but it looks like the trend overall is just to use npm tasks :jack_o_lantern:
