### ISSUE TITLE
Version in NPM registry not stable

### ISSUE THREAD

**Issue by joshrickert** [omouse/grunt2gulp.js#19]
I tried to install from the npm registry, but the installation failed because that version is missing commit 2a7c37e. Installing from master off github fixed it, but you probably want the version on NPM to be a stable release.

**Comment by digitaljhelms** [comment]
+1

**Comment by omouse** [comment]
just tagged and added some release notes, about to push to npm for version 0.0.2 which includes that commit: https://github.com/omouse/grunt2gulp.js/releases/tag/0.0.2-cool-card

**Comment by omouse** [comment]
@digitaljhelms @joshrickert should be able to pull 0.0.2 from npm now
