### ISSUE TITLE
Usage question.

### ISSUE THREAD

**Issue by alisamii** [omouse/grunt2gulp.js#5]
Hi,

I'm not sure how to use this package. If I need to convert dozens of gruntfile.js filesinto gulpfile.js files across a large Repo of multiple projects, how do I:

1. Install this package as there is no npm install as best I can tell, and
2. How do I call the package so that it executes because I tried the syntax in the readme docs and it exitted with an error.

Thanks for your reply at your earliest convenience.

**Comment by anotherZero** [comment]
I figured it out.  I was able to run this using the following:

```
node grunt2gulp.js
```

Most *nix systems won't just let you execute a file unless the permissions are +x so you have to tell it what to process it with.  (theoretically it could be run using something like `bash grunt2gulp.js` but it's going to process with node anyway so just use `node`)

**Comment by alisamii** [comment]
I tried that and it didn't work. The problem is I'm not sure where to install the package so it is available globally. If I need to clone the git repo in each project, might add well manually write the gulpfile.js in each project as well.

**Comment by anotherZero** [comment]
all you need is the raw js file to be able to run it.  
https://raw.githubusercontent.com/omouse/grunt2gulp.js/master/bin/grunt2gulp.js 
put it in a directory then run 
``` 
node /path/to/grunt2gulp.js /path/to/Gruntfile.js > /path/to/converted-gulpfile.js
```
